apiVersion: v1
kind: Namespace
metadata:
  name: interview

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interviewdb
  namespace: interview
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      app: interviewdb
      version: 'v1'
  template:
    metadata:
      labels:
        app: interviewdb
        version: 'v1'
    spec:
      containers:
        - name: interviewdb
          image: vamsikkv/interviewdb:7
          env:
            - name: _JAVA_OPTIONS
              value: "-Xmx1024m -Xms512m"
            - name: SPRING_PROFILES_ACTIVE
              value: prod,swagger
            - name: Dhttps.protocols
              value: "TLSv1.2"
            - name: MANAGEMENT_METRICS_EXPORT_PROMETHEUS_ENABLED
              value: "true"
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://35.184.231.6:5432/interviewdb"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "lorem@Ipsum"
            - name: SPRING_DATASOURCE_HIKARI_MAXIMUM_POOL_SIZE
              value: "5"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_PROVIDER_OIDC_ISSUER_URI
              value: "https://intervu.tech/auth/realms/intervu"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_ID
              value: "web-app"
            - name: SPRING_SECURITY_OAUTH2_CLIENT_REGISTRATION_OIDC_CLIENT_SECRET
              value: "web-app"
          ports:
            - name: http
              containerPort: 9600

#          resources:
#            requests:
#              memory: '512Mi'
#              cpu: '500m'
#            limits:
#              memory: '1Gi'
#              cpu: '1'
          readinessProbe:
            httpGet:
              path: /management/health
              port: 9600
            initialDelaySeconds: 20
            periodSeconds: 15
            failureThreshold: 6
          livenessProbe:
            httpGet:
              path: /management/health
              port: 9600
            initialDelaySeconds: 120


